name: Docker Image CI

on:
  schedule:
    - cron: '0 */12 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check if image is fresh
      run: docker run --rm -it ghcr.io/richlander/lucy:main ghcr.io/richlander/lucy:main mcr.microsoft.com/dotnet/nightly/runtime:7.0-jammy-chiseled
