name: Image freshness check

on:
  workflow_dispatch:
  schedule:
    - cron: '15 */12 * * *'

jobs:

  freshness-check:

    runs-on: ubuntu-latest

    steps:
    - name: Check if image is fresh
      id: check
      uses: richlander/container-base-image-check-action@main
      with:
        image: ghcr.io/richlander/lucy:main
        base-image: mcr.microsoft.com/dotnet/runtime:7.0    
    - name: Print result
      run: echo "Image is ${{steps.check.outputs.state}}"
    - name: Invoke workflow without inputs
      uses: benc-uk/workflow-dispatch@v1
      if: ${{ steps.check.outputs.state == 'stale' }}
      with:
        workflow: Docker
        token: ${{ secrets.PAT }}        
