name: Image freshness check

on:
  workflow_dispatch:
  schedule:
    - cron: '15 */12 * * *'

jobs:

  freshness-check:

    runs-on: ubuntu-latest

    steps:
    - name: Check if image is fresh
      run: docker run --rm ghcr.io/richlander/lucy:main ghcr.io/richlander/lucy:main mcr.microsoft.com/dotnet/nightly/runtime:7.0-jammy-chiseled > result.txt
    - name: Collect result
      run: echo "freshness=$(cat result.txt)" >> $GITHUB_ENV
    - name: Print result
      run: echo "Image is $freshness"
    - name: Invoke workflow without inputs
      uses: benc-uk/workflow-dispatch@v1
      if: ${{ env.freshness == 'stale' }}
      with:
        workflow: Docker
        token: ${{ secrets.PAT }}        
